#!/bin/bash

# sinit - Sourim Init System
# Copyright (C) 2024 r2u2team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

COLOR_RESET="\e[0m"
COLOR_BOLD="\e[1m"
COLOR_RED="\e[31m"
COLOR_GREEN="\e[32m"
COLOR_BLUE="\e[34m"
COLOR_CYAN="\e[36m"
COLOR_YELLOW="\e[1;33m"

echo -e "Welcome to ${COLOR_CYAN}SourimLinux${COLOR_RESET}!"

log() {
    echo -ne "\r[$1${COLOR_RESET}] ${COLOR_BOLD}$2${COLOR_RESET}"
}
svstart() {
    log "${COLOR_YELLOW}WAITING" "Starting '$1'"
    sctl start /etc/rc.d/$2/$1
    
    if [[ $? == 0 ]]; then
        log "${COLOR_GREEN}SUCCESS" "Starting '$1'\n"
    else
        log " ${COLOR_RED}ERROR " "Starting '$1'\n"
    fi
}

for i in $(ls /etc/rc.d/init.d); do
    svstart $i init.d
done

for r in $(ls /etc/rc.d/run.d); do
    svstart $r run.d
done