#!/bin/bash

# sinit - Sourim Init System
# Copyright (C) 2024 r2u2team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

echo "Welcome to SourimLinux!"

for i in $(ls /etc/rc.d/init.d); do
    echo -n "[WAITING] Starting init '$i'"
    /etc/rc.d/init.d/$i start &
    wait
    
    if [[ $? == 0 ]]; then
        echo -e "\r[SUCCESS] Starting init '$i'"
    else
        echo -e "\r[ ERROR ] Starting init '$i'"
    fi
done

while true; do
    /bin/bash
done