#!/bin/bash

case "$1" in
    start)
        mount -t devtmpfs -o mode=0755,nosuid none /dev
        mount -t sysfs -o nosuid,noexec,nodev none /sys
        mount -t proc -o nosuid,noexec,nodev none /proc

        exit $?
    ;;
    *)
        echo "Usage: $0 {start}"
        exit 1
    ;;
esac